DROP DATABASE IF EXISTS miCareer_DB;
CREATE DATABASE miCareer_DB
CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE miCareer_DB;

CREATE TABLE Region (
    regId VARCHAR(20) PRIMARY KEY,
    regName VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Province (
    provId VARCHAR(10) PRIMARY KEY,
    provName VARCHAR(80) NOT NULL UNIQUE,
    regId VARCHAR(20) NOT NULL,
    FOREIGN KEY (regId) REFERENCES Region(regId) ON DELETE CASCADE
);

CREATE TABLE HRPosition (
    posId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    posName VARCHAR(50) NOT NULL UNIQUE,
    `desc` VARCHAR(500)
);

CREATE TABLE AdminRole (
    roleId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    roleName VARCHAR(50) NOT NULL UNIQUE,
    `desc` VARCHAR(500)
);

CREATE TABLE Permission (
    permId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    permCode VARCHAR(50) NOT NULL UNIQUE,
    `desc` VARCHAR(500)
);

CREATE TABLE Skill (
    skillId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    skillName VARCHAR(50) NOT NULL UNIQUE,
    `desc` VARCHAR(500)
);

CREATE TABLE EmailType (
    typeId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    typeName VARCHAR(50) NOT NULL UNIQUE,
    `desc` VARCHAR(500)
);

CREATE TABLE JobCategory (
    catId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    catName VARCHAR(100) NOT NULL UNIQUE,
    `desc` VARCHAR(500)
);

CREATE TABLE JobLevel (
    levelId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    levelName VARCHAR(50) NOT NULL UNIQUE,
    `desc` VARCHAR(500)
);

CREATE TABLE RolePermission (
    roleId INT UNSIGNED,
    permId INT UNSIGNED,
    PRIMARY KEY (roleId, permId),
    FOREIGN KEY (roleId) REFERENCES AdminRole(roleId) ON DELETE CASCADE,
    FOREIGN KEY (permId) REFERENCES Permission(permId) ON DELETE CASCADE
);

CREATE TABLE EmailTemplate (
    tmplId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    typeId INT UNSIGNED,
    subj VARCHAR(200),
    body TEXT,
    `desc` VARCHAR(500),
    FOREIGN KEY (typeId) REFERENCES EmailType(typeId) ON DELETE CASCADE
);

CREATE TABLE `User` (
    userId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    userName VARCHAR(50) NOT NULL UNIQUE,
    pwd VARCHAR(300) NOT NULL,
    fName VARCHAR(50),
    lName VARCHAR(50),
    email VARCHAR(400) NOT NULL UNIQUE,
    phone VARCHAR(20),
    stat ENUM('ACTIVE', 'INACTIVE', 'BANNED', 'PENDING') NOT NULL DEFAULT 'ACTIVE',
    `role` VARCHAR(30) NOT NULL,
    provId VARCHAR(10),
    ward VARCHAR(80),
    street VARCHAR(150),
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (provId) REFERENCES Province(provId) ON DELETE CASCADE
);

CREATE TABLE Company (
    compId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    compName VARCHAR(200) NOT NULL,
    taxCode VARCHAR(20) UNIQUE,
    webUrl VARCHAR(500),
    logoUrl VARCHAR(500),
    contactEmail VARCHAR(400),
    provId VARCHAR(10),
    ward VARCHAR(80),
    street VARCHAR(150),
    FOREIGN KEY (provId) REFERENCES Province(provId) ON DELETE CASCADE
);

CREATE TABLE Candidate (
    candidateId INT UNSIGNED PRIMARY KEY,
    bio TEXT,
    cvUrl VARCHAR(500),
    dob DATE,
    expYears DECIMAL(4,1),
    FOREIGN KEY (candidateId) REFERENCES `User`(userId) ON DELETE CASCADE
);

CREATE TABLE HR (
    hrId INT UNSIGNED PRIMARY KEY,
    posId INT UNSIGNED,
    compId INT UNSIGNED,
    FOREIGN KEY (hrId) REFERENCES `User`(userId) ON DELETE CASCADE,
    FOREIGN KEY (posId) REFERENCES HRPosition(posId) ON DELETE CASCADE,
    FOREIGN KEY (compId) REFERENCES Company(compId) ON DELETE CASCADE
);

CREATE TABLE Admin (
    adminId INT UNSIGNED PRIMARY KEY,
    roleId INT UNSIGNED,
    FOREIGN KEY (adminId) REFERENCES `User`(userId) ON DELETE CASCADE,
    FOREIGN KEY (roleId) REFERENCES AdminRole(roleId) ON DELETE CASCADE
);

CREATE TABLE CandidateSkill (
    candidateId INT UNSIGNED,
    skillId INT UNSIGNED,
    PRIMARY KEY (candidateId, skillId),
    FOREIGN KEY (candidateId) REFERENCES Candidate(candidateId) ON DELETE CASCADE,
    FOREIGN KEY (skillId) REFERENCES Skill(skillId) ON DELETE CASCADE
);

CREATE TABLE JobPosting (
    jobPostId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    compId INT UNSIGNED,
    title VARCHAR(150) NOT NULL,
    `desc` LONGTEXT NOT NULL,
    minSalary DECIMAL(15,2),
    maxSalary DECIMAL(15,2),
    workLoc VARCHAR(150),
    workMode VARCHAR(30),
    stat ENUM('DRAFT', 'PUBLISHED', 'CLOSED', 'EXPIRED') DEFAULT 'DRAFT',
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    expAt DATETIME,
    catId INT UNSIGNED,
    levelId INT UNSIGNED,
    hrId INT UNSIGNED,
    FOREIGN KEY (compId) REFERENCES Company(compId) ON DELETE CASCADE,
    FOREIGN KEY (catId) REFERENCES JobCategory(catId) ON DELETE CASCADE,
    FOREIGN KEY (levelId) REFERENCES JobLevel(levelId) ON DELETE CASCADE
);

CREATE TABLE JobRequirement (
    jobPostId INT UNSIGNED,
    skillId INT UNSIGNED,
    PRIMARY KEY (jobPostId, skillId),
    FOREIGN KEY (jobPostId) REFERENCES JobPosting(jobPostId) ON DELETE CASCADE,
    FOREIGN KEY (skillId) REFERENCES Skill(skillId) ON DELETE CASCADE
);

CREATE TABLE JobApplication (
    jobAppId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    jobPostId INT UNSIGNED,
    candidateId INT UNSIGNED,
    appliedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    stat ENUM('PENDING', 'REVIEWING', 'INTERVIEWING', 'ACCEPTED', 'REJECTED') DEFAULT 'PENDING',
    cvSnapUrl VARCHAR(500),
    coverLetter TEXT,
    FOREIGN KEY (jobPostId) REFERENCES JobPosting(jobPostId) ON DELETE CASCADE,
    FOREIGN KEY (candidateId) REFERENCES Candidate(candidateId) ON DELETE CASCADE,
    UNIQUE (jobPostId, candidateId)
);

CREATE TABLE AppStatusHistory (
    histId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    jobAppId INT UNSIGNED,
    hrId INT UNSIGNED,
    oldStat ENUM('PENDING', 'REVIEWING', 'INTERVIEWING', 'ACCEPTED', 'REJECTED'),
    newStat ENUM('PENDING', 'REVIEWING', 'INTERVIEWING', 'ACCEPTED', 'REJECTED'),
    changeAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (jobAppId) REFERENCES JobApplication(jobAppId) ON DELETE CASCADE,
    FOREIGN KEY (hrId) REFERENCES HR(hrId) ON DELETE CASCADE
);

CREATE TABLE Interview (
    intervId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    jobAppId INT UNSIGNED,
    title VARCHAR(100),
    startAt DATETIME,
    endAt DATETIME,
    stat ENUM('SCHEDULED', 'COMPLETED', 'CANCELED') DEFAULT 'SCHEDULED',
    mode VARCHAR(30),
    linkMeet VARCHAR(500),
    loc VARCHAR(150),
    FOREIGN KEY (jobAppId) REFERENCES JobApplication(jobAppId) ON DELETE CASCADE
);

CREATE TABLE InterviewFeedback (
    feedbackId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    intervId INT UNSIGNED,
    hrId INT UNSIGNED,
    score DECIMAL(4,2),
    cmt TEXT,
    subAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (intervId) REFERENCES Interview(intervId) ON DELETE CASCADE,
    FOREIGN KEY (hrId) REFERENCES HR(hrId) ON DELETE CASCADE
);

CREATE TABLE Offer (
    offerId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    jobAppId INT UNSIGNED,
    salary DECIMAL(15,2),
    `desc` TEXT,
    stat ENUM('PENDING', 'ACCEPTED', 'REJECTED') DEFAULT 'PENDING',
    version INT,
    hrId INT UNSIGNED,
    FOREIGN KEY (jobAppId) REFERENCES JobApplication(jobAppId) ON DELETE CASCADE,
    FOREIGN KEY (hrId) REFERENCES HR(hrId) ON DELETE CASCADE
);

CREATE TABLE EmailLog (
    logId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    tmplId INT UNSIGNED,
    jobAppId INT UNSIGNED,
    userId INT UNSIGNED,
    content TEXT,
    sentAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    rcvEmail VARCHAR(400),
    FOREIGN KEY (tmplId) REFERENCES EmailTemplate(tmplId) ON DELETE CASCADE,
    FOREIGN KEY (jobAppId) REFERENCES JobApplication(jobAppId) ON DELETE CASCADE,
    FOREIGN KEY (userId) REFERENCES `User`(userId) ON DELETE CASCADE
);
